# Where the homeserver's Client-Server API is located. Typically this
# is where clients would be connecting to in order to send messages.
homeserverUrl: "https://matrix.org"

# An access token for the bot to use. Learn how to get an access token
# at https://t2bot.io/docs/access_tokens
accessToken: "YOUR_TOKEN_HERE"

# Whether or not to autojoin rooms when invited.
autoJoin: true

# Location on disk for where to store various bot information.
dataPath: "storage"

# Options for configuring the EarthClassMail side of the bridge.
earthClassMail:
  # The API URL to use. This shouldn't change.
  apiUrl: "https://api.earthclassmail.com"

  # Your username and password for ECM. Note that an ECM API Key
  # is not enough access to be able to perform actions as you.
  username: "email@example.org"
  password: "s3cret"

  # The inbox ID to use. If zero or negative, the bridge will assume
  # the first returned mailbox is the one to use (this is the case for
  # most setups).
  inboxId: 0
