# Options for configuring the Matrix side of the bridge.
matrix:
  # For received letters, these are the default profile settings.
  defaultAvatar: "mxc://t2bot.io/183b28d9d10511e3c8b937674168c1de604076c0"
  defaultName: "Letter"

  # Where to send management information regarding the bot. This includes
  # unroutable mail notifications.
  managementRoom: "!room:example.org"

  # The appservice registration information
  appservice:
    # The HS and AS tokens. You should generate these.
    hsToken: "GENERATE_ME"
    asToken: "GENERATE_ME"

    # The prefix to use for received letters.
    userPrefix: "postal_"

    # The localpart for the bot
    botLocalpart: "postmaster"

    # The domain for which the appservice is hosted
    domain: "localhost"

    # The webserver's listener configuration
    address: "0.0.0.0"
    port: 8080

    # Where to access the homeserver's client-server API.
    csUrl: "https://localhost:8448"

    # Where to store miscellaneous information about the appservice.
    dataPath: "storage"

    # Where static assets are served/read by the bridge. Should be near the templates.
    assetsPath: "tmpl/assets"

    # Profile information for the bot itself.
    botName: "Postmaster"
    botAvatar: "mxc://t2bot.io/b741b75047dfbde0470a93566325de2e54b439e0"

# Options for configuring the EarthClassMail side of the bridge.
earthClassMail:
  # The API URL to use. This shouldn't change.
  apiUrl: "https://api.earthclassmail.com"

  # Your username and password for ECM. Note that an ECM API Key
  # is not enough access to be able to perform actions as you.
  username: "email@example.org"
  password: "s3cret"

  # The inbox ID to use. If zero or negative, the bridge will assume
  # the first returned mailbox is the one to use (this is the case for
  # most setups).
  inboxId: 0

# Options for configuring the Lob side of the bridge.
lob:
  # The secret API key for your lob account. Get this from Settings -> API Keys
  apiKey: "from_lob"

  # The maximum number of rooms to allow users to subscribe to.
  maxRooms: 7

  # The maximum number of most recent messages in a room to consider for rendering.
  maxMessagesPerRoom: 3

# The postgresql database settings for the bridge to use.
database:
  host: "localhost"
  port: 5432
  username: "lettermail"
  password: "s3cret"
  database: "lettermail"
  sslmode: "require"
